blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/RealMikeChong/ultra-mcp/blob/main/README.md
    about: Check the documentation for setup guides and examples
  - name: Discussions
    url: https://github.com/RealMikeChong/ultra-mcp/discussions
    about: Ask questions and discuss ideas with the community