name: Feature request
description: Suggest an idea for Ultra MCP
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature for Ultra MCP!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - AI Model Integration
        - CLI Commands
        - MCP Tools
        - Configuration & Setup
        - Usage Tracking & Analytics
        - Documentation
        - Performance & Optimization
        - Developer Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve my workflow
        - High - Critical for my use case
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        How would you use this feature?
        What workflow would it improve?
        What problem would it solve for you?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: If applicable, provide examples of how this feature might work
      placeholder: |
        Command examples:
        ```bash
        npx -y ultra-mcp your-new-feature --option value
        ```
        
        Or tool usage examples, configuration snippets, etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with Ultra MCP's goal of providing a unified AI model interface
          required: true
        - label: I would be willing to help test this feature when available
          required: false