name: General issue
description: General questions, discussions, or other issues
title: "[General]: "
labels: ["question", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Use this template for general questions, discussions, or issues that don't fit the bug report or feature request categories.

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question / Help Needed
        - Documentation Issue
        - Configuration Problem
        - Installation Problem
        - Performance Question
        - Integration Help
        - General Discussion
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your question or issue in detail
      placeholder: |
        What do you need help with?
        What are you trying to achieve?
        What's not working as expected?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your setup or use case
      placeholder: |
        - What are you trying to do?
        - What have you tried so far?
        - Any relevant configuration or setup details?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Node.js version: [e.g., 20.10.0]
        - Ultra MCP version: [e.g., 0.5.0]
        - Installation method: [npm, npx, local build]

  - type: textarea
    id: output
    attributes:
      label: Relevant Output or Logs
      description: If applicable, add any output, logs, or error messages
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other information that might be helpful

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and documentation
          required: true
        - label: I have removed any sensitive information (API keys, tokens, etc.)
          required: true